### ISSUE TITLE
Error por resolucion fija

### ISSUE THREAD

**Issue by arksega** [LinuxCabal/LCUtils#7]
Si la configuración del monitor no es 1920x1080 la grabación falla

**Comment by renich** [comment]
Ya sé que no tenemos config file, pero hay una sección de config en `mkscreencast`. La variable `resolution` tiene hardcodeado el valor '1920x1080'.

Probaste cambiarlo?

**Comment by renich** [comment]
@arksega: chécate:

`ffmpeg -loglevel verbose -threads auto -f pulse -i default -f x11grab -s 1920x1080 -i :1 -c:v libvpx -deadline good -cpu-used 4 -b:v 500k -qmin 10 -qmax 42 -maxrate 500k -bufsize 1000k -skip_threshold 50 -c:a libvorbis -b:a 128k /home/renich/Videos/screencasts/20160229-225625-test.webm`

Ese es el comando que se usa al encodear un screencast en tiempo real. Alguna idea para mejorarlo?

**Comment by renich** [comment]
Con alguno de los cambios que hice, ya jala, hehe. No supe en dónde estuvo el cotorreo...
